"use strict";
let car = "subaru";
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'Honda'? I predict False.");
console.log(car == 'Honda');
console.log("Is car == 'Subaru'? I predict False.");
console.log(car == 'Subaru');
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
console.log("Is car != 'Honda'? I predict True.");
console.log(car != 'Honda');
console.log("Is car != 'Toyota'? I predict True.");
console.log(car != 'Toyota');
console.log("Is car == 'Toyota'? I predict False.");
console.log(car == 'Toyota');
console.log("Is car == 'Alsvin'? I predict False.");
console.log(car == 'Alsvin');
console.log("Is car != 'Alsvin'? I predict True.");
console.log(car != 'Alsvin');
console.log("Is car != 'BMW'? I predict True.");
console.log(car != 'BMW');
